PracticaMvcCore2AGC/ViewComponents/CarritoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2AGC.Models;
using PracticaMvcCore2AGC.Repositorys;

namespace PracticaMvcCore2AGC.ViewComponents
{
    public class CarritoViewComponent : ViewComponent
    {
        private LibrosRepository repo;

        public CarritoViewComponent(LibrosRepository repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            string sesion = HttpContext.Session.GetString("CARRITO");
            if (sesion != null)
            {
                @ViewData["CUENTA"] = this.repo.GetLibrosCarrito(sesion).Count();
            }
            else
            {
                @ViewData["CUENTA"] = 0;

            }
            return View();
        }
    }
}

PracticaMvcCore2AGC/ViewComponents/MenuGenerosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2AGC.Models;
using PracticaMvcCore2AGC.Repositorys;

namespace PracticaMvcCore2AGC.ViewComponents
{
    public class MenuGenerosViewComponent : ViewComponent
    {
        private LibrosRepository repo;

        public MenuGenerosViewComponent(LibrosRepository repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Genero> gen = this.repo.GetGeneros();
            return View(gen);
        }
    }
}

PracticaMvcCore2AGC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaMvcCore2AGC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaMvcCore2AGC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-route-id="0" asp-controller="Home" asp-action="Index">PracticaMvcCore2AGC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-route-id="0" asp-area="" asp-controller="Home" asp-action="Index">Libros</a>
                        </li>
                        @await Component.InvokeAsync("MenuGeneros")
                        @await Component.InvokeAsync("Carrito")
                        @if(Context.User.Identity.Name == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Managed" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Perfil">MiPerfil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Managed" asp-action="Logout">LogOut</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PracticaMvcCore2AGC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>